.TH "Laravel" 3 "Fri May 3 2019" "Control de citas; Universidad Marista" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Laravel \- \fBLaravel\fP - A PHP Framework For Web Artisans\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBLaravel\fP - A PHP Framework For Web Artisans\&. 


.PP
\fBAuthor:\fP
.RS 4
Taylor Otwell taylor@laravel.com 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Control de citas; Universidad Marista from the source code\&.
