.TH "md_AppConsultas_readme" 3 "Fri May 3 2019" "Control de citas; Universidad Marista" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_AppConsultas_readme \- readme 

.PP
\fC\fP \fC\fP \fC\fP \fC\fP 
.PP
.SS "About \fBLaravel\fP"
.PP
\fBLaravel\fP is a web application framework with expressive, elegant syntax\&. We believe development must be an enjoyable and creative experience to be truly fulfilling\&. \fBLaravel\fP takes the pain out of development by easing common tasks used in many web projects, such as:
.PP
.IP "\(bu" 2
\fCSimple, fast routing engine\fP\&.
.IP "\(bu" 2
\fCPowerful dependency injection container\fP\&.
.IP "\(bu" 2
Multiple back-ends for \fCsession\fP and \fCcache\fP storage\&.
.IP "\(bu" 2
Expressive, intuitive \fCdatabase ORM\fP\&.
.IP "\(bu" 2
Database agnostic \fCschema migrations\fP\&.
.IP "\(bu" 2
\fCRobust background job processing\fP\&.
.IP "\(bu" 2
\fCReal-time event broadcasting\fP\&.
.PP
.PP
\fBLaravel\fP is accessible, powerful, and provides tools required for large, robust applications\&.
.PP
.SS "Learning \fBLaravel\fP"
.PP
\fBLaravel\fP has the most extensive and thorough \fCdocumentation\fP and video tutorial library of all modern web application frameworks, making it a breeze to get started with the framework\&.
.PP
If you don't feel like reading, \fCLaracasts\fP can help\&. Laracasts contains over 1100 video tutorials on a range of topics including \fBLaravel\fP, modern PHP, unit testing, and JavaScript\&. Boost you and your team's skills by digging into our comprehensive video library\&.
.PP
.SS "\fBLaravel\fP Sponsors"
.PP
We would like to extend our thanks to the following sponsors for funding \fBLaravel\fP development\&. If you are interested in becoming a sponsor, please visit the \fBLaravel\fP \fCPatreon page\fP\&.
.PP
.IP "\(bu" 2
\fB\fCVehikl\fP\fP
.IP "\(bu" 2
\fB\fCTighten Co\&.\fP\fP
.IP "\(bu" 2
\fB\fCKirschbaum Development Group\fP\fP
.IP "\(bu" 2
\fB\fC64 Robots\fP\fP
.IP "\(bu" 2
\fB\fCCubet Techno Labs\fP\fP
.IP "\(bu" 2
\fB\fCCyber-Duck\fP\fP
.IP "\(bu" 2
\fB\fCBritish Software Development\fP\fP
.IP "\(bu" 2
\fB\fCWebdock, Fast VPS Hosting\fP\fP
.IP "\(bu" 2
\fB\fCDevSquad\fP\fP
.IP "\(bu" 2
\fCUserInsights\fP
.IP "\(bu" 2
\fCFragrantica\fP
.IP "\(bu" 2
\fCSOFTonSOFA\fP
.IP "\(bu" 2
\fCUser10\fP
.IP "\(bu" 2
\fCSoumettre\&.fr\fP
.IP "\(bu" 2
\fCCodeBrisk\fP
.IP "\(bu" 2
\fC1Forge\fP
.IP "\(bu" 2
\fCTECPRESSO\fP
.IP "\(bu" 2
\fCRuntime Converter\fP
.IP "\(bu" 2
\fCWebL'Agence\fP
.IP "\(bu" 2
\fCInvoice Ninja\fP
.IP "\(bu" 2
\fCiMi digital\fP
.IP "\(bu" 2
\fCEarthlink\fP
.IP "\(bu" 2
\fCSteadfast Collective\fP
.IP "\(bu" 2
\fCWe Are The Robots Inc\&.\fP
.IP "\(bu" 2
\fCUnderstand\&.io\fP
.IP "\(bu" 2
\fCAbdel Elrafa\fP
.PP
.PP
.SS "Contributing"
.PP
Thank you for considering contributing to the \fBLaravel\fP framework! The contribution guide can be found in the \fCLaravel documentation\fP\&.
.PP
.SS "Security Vulnerabilities"
.PP
If you discover a security vulnerability within \fBLaravel\fP, please send an e-mail to Taylor Otwell via \fCtaylor@laravel\&.com\fP\&. All security vulnerabilities will be promptly addressed\&.
.PP
.SS "License"
.PP
The \fBLaravel\fP framework is open-source software licensed under the \fCMIT license\fP\&. 
